version: "3.8"
services:
  client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map cổng 3000 (host) sang 80 (container)
    depends_on:
      - server

  server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Map cổng 8081
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./back-end:/app # Để hỗ trợ live development
    restart: always  

