version: "3.8"
services:
  frontend-app:  # Đổi tên từ 'client' thành 'frontend-app'
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map cổng 3000 của host sang cổng 80 của container
    depends_on:
      - backend-app  # Cập nhật tên dịch vụ phụ thuộc
    volumes:
      - ./front-end/publics:/app/publics # Gắn thư mục public riêng cho frontend
      - shared:/app/shared # Gắn volume chung vào frontend

  backend-app:  # Đổi tên từ 'server' thành 'backend-app'
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Map cổng 8081
    volumes:
      - ./back-end/publics:/app/publics # Gắn thư mục public riêng cho backend
      - shared:/app/shared # Gắn volume chung vào backend
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
    restart: always

volumes:
  shared:  # Volume dùng chung giữa frontend và backend
